services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/modelo_efficientnet_final.keras:/app/modelo_efficientnet_final.keras
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
